anchor:
  anchor_size: 8
  aspect_ratios: [1.0, 2.0, 0.5]
  num_scales: 1
architecture:
  backbone: resnet
  include_mask: true
  mask_target_size: 28
  max_level: 6
  min_level: 2
  multilevel_features: fpn
  num_classes: 91
  parser: maskrcnn_parser
  pre_parser: null
  space_to_depth_block_size: 1
  use_bfloat16: false
batch_norm_activation:
  activation: relu
  batch_norm_epsilon: 0.0001
  batch_norm_momentum: 0.997
  batch_norm_trainable: true
  use_sync_bn: false
dropblock:
  dropblock_keep_prob: null
  dropblock_size: null
enable_summary: false
eval:
  eval_batch_size: 8
  eval_dataset_type: tfrecord
  eval_file_pattern: ~/data/datasets/Fashionpedia/tf_record/val
  eval_samples: null
  eval_timeout: null
  min_eval_interval: 180
  num_steps_per_eval: 1000
  per_category_metrics: false
  skip_eval_loss: false
  type: box_and_mask
  use_json_file: true
  val_json_file: ~/data/datasets/Fashionpedia/annotations/instances_attributes_val2020.json
fpn:
  fpn_feat_dims: 256
  use_batch_norm: true
  use_separable_conv: false
frcnn_box_loss:
  huber_loss_delta: 1.0
frcnn_head:
  fc_dims: 1024
  num_convs: 0
  num_fcs: 2
  num_filters: 256
  use_batch_norm: false
  use_separable_conv: false
isolate_session_state: false
mask_sampling:
  num_mask_samples_per_image: 128
maskrcnn_parser:
  aug_rand_hflip: true
  aug_scale_max: 1.0
  aug_scale_min: 1.0
  mask_crop_size: 112
  max_num_instances: 100
  output_size: [1024, 1024]
  rpn_batch_size_per_im: 256
  rpn_fg_fraction: 0.5
  rpn_match_threshold: 0.7
  rpn_unmatched_threshold: 0.3
  skip_crowd_during_training: true
model_dir: ~/Vision/git/tpu/output_models
mrcnn_head:
  num_convs: 4
  num_filters: 256
  use_batch_norm: false
  use_separable_conv: false
postprocess:
  apply_nms: true
  max_total_size: 100
  nms_iou_threshold: 0.5
  nms_version: v1
  pre_nms_num_boxes: 1000
  score_threshold: 0.05
  use_batched_nms: false
predict:
  predict_batch_size: 8
resnet:
  init_drop_connect_rate: null
  resnet_depth: 50
roi_proposal:
  rpn_min_size_threshold: 0.0
  rpn_nms_threshold: 0.7
  rpn_post_nms_top_k: 1000
  rpn_pre_nms_top_k: 2000
  rpn_score_threshold: 0.0
  test_rpn_min_size_threshold: 0.0
  test_rpn_nms_threshold: 0.7
  test_rpn_post_nms_top_k: 1000
  test_rpn_pre_nms_top_k: 1000
  test_rpn_score_threshold: 0.0
  use_batched_nms: false
roi_sampling:
  bg_iou_thresh_hi: 0.5
  bg_iou_thresh_lo: 0.0
  fg_fraction: 0.25
  fg_iou_thresh: 0.5
  mix_gt_boxes: true
  num_samples_per_image: 512
rpn_box_loss:
  huber_loss_delta: 0.1111111111111111
rpn_head:
  anchors_per_location: null
  num_convs: 1
  num_filters: 256
  use_batch_norm: false
  use_separable_conv: false
rpn_score_loss:
  rpn_batch_size_per_im: 256
train:
  checkpoint:
    path: gs://cloud-tpu-artifacts/resnet/resnet-nhwc-2018-10-14/model.ckpt-112602
    prefix: resnet50/
    skip_variables_regex: ''
  frozen_variable_prefix: null
  gradient_clip_norm: 0.0
  input_partition_dims: null
  iterations_per_loop: 100
  l2_weight_decay: 0.0001
  learning_rate:
    init_learning_rate: 0.08
    learning_rate_levels: [0.008, 0.0008]
    learning_rate_steps: [15000, 20000]
    type: step
    warmup_learning_rate: 0.0067
    warmup_steps: 500
  num_cores_per_replica: null
  optimizer:
    momentum: 0.9
    type: momentum
  regularization_variable_regex: .*(kernel|weight):0$
  space_to_depth_block_size: 1
  total_steps: 22500
  train_batch_size: 64
  train_dataset_type: tfrecord
  train_file_pattern: ~/data/datasets/Fashionpedia/tf_record/train
  transpose_input: true
type: mask_rcnn
use_tpu: false
